library: library.db
directory: ~/music

plugins: [play, random, info, musicbrainz, lyrics, duplicates, fetchart, lastgenre, zero, scrub]

import:
  copy: no
  move: yes

replace:
  '[\\/]': _
  ^\.: _
  '[\x00-\x1f]': _
  '[<>:"\?\*\|]': _
  \.$: _
  \s+$: ""
  ^\s+: ""
  ^-: _

paths:
  default: $albumartist/$album%aunique{}/$track $title
  singleton: Non-Album/$artist/$title
  comp: Compilations/$album%aunique{}/$track $title

ui:
  colors:
    text_success: green
    text_warning: yellow
    text_error: red
    text_highlight: red
    text_highlight_minor: lightgray
    action_default: turquoise
    action: blue

format_item: $artist - $album - $title
format_album: $albumartist - $album
sort_album: albumartist+ album+
sort_item: artist+ album+ disc+ track+
sort_case_insensitive: yes

play:
  command: mpv --no-audio-display $args

zero:
  fields: comments
  update_database: true

fetchart:
  auto: yes

lastgenre:
  count: 2

scrub:
  auto: yes