-- patroclus -- neovim palette and lualine theme.
--
-- GENERATED by tools/gen_tokens.py in the patroclus repo, from its
-- design.yaml. Do not edit here; change design.yaml and regenerate.
--
-- `colors` is the palette the colorscheme paints with. The generic names
-- at the end (fg, orange, violet, ...) are aliases the galactus
-- statusline speaks, so its layout needs no mapping table of its own.

local M = {}

M.colors = {
  bg              = "#000000",
  surface         = "#0b0e12",
  surface_soft    = "#13171c",
  line            = "#2e333b",
  text            = "#abb2b9",
  headline        = "#f2efe9",
  muted           = "#8f969d",
  selection       = "#3a2318",
  copper          = "#cf7d55",
  steel           = "#669ac5",
  alizarin        = "#a51c30",
  sage            = "#719e58",
  ochre           = "#bf9932",
  verdigris       = "#37a19e",
  plum            = "#c081aa",
  red             = "#d33949",
  ln              = "#7f868d",
  hl              = "#13171c",
  comment         = "#72797f",
  ins_bg          = "#0c151d",
  del_bg          = "#190407",
  chg_bg          = "#1f130d",
  bright_black    = "#50565c",
  bright_red      = "#ea696e",
  bright_green    = "#93c179",
  bright_yellow   = "#dfb956",
  bright_blue     = "#79b8ed",
  bright_magenta  = "#d599d8",
  bright_cyan     = "#5fc4c0",
  bright_white    = "#f2efe9",
  fg              = "#abb2b9",
  subtext         = "#8f969d",
  green           = "#719e58",
  yellow          = "#bf9932",
  orange          = "#cf7d55",
  blue            = "#cf7d55",
  darkblue        = "#669ac5",
  cyan            = "#5fc4c0",
  teal            = "#37a19e",
  violet          = "#c081aa",
  magenta         = "#d599d8",
}

local c = M.colors

-- lualine. galactus overrides the `c` section itself, but a complete
-- theme means the bar can never drift from the editor.
M.lualine = {
  normal = {
    a = { fg = c.bg, bg = c.copper, gui = "bold" },
    b = { fg = c.text, bg = c.surface },
    c = { fg = c.text, bg = c.bg },
  },
  insert = {
    a = { fg = c.bg, bg = c.sage, gui = "bold" },
    b = { fg = c.text, bg = c.surface },
    c = { fg = c.text, bg = c.bg },
  },
  visual = {
    a = { fg = c.bg, bg = c.plum, gui = "bold" },
    b = { fg = c.text, bg = c.surface },
    c = { fg = c.text, bg = c.bg },
  },
  replace = {
    a = { fg = c.bg, bg = c.red, gui = "bold" },
    b = { fg = c.text, bg = c.surface },
    c = { fg = c.text, bg = c.bg },
  },
  command = {
    a = { fg = c.bg, bg = c.ochre, gui = "bold" },
    b = { fg = c.text, bg = c.surface },
    c = { fg = c.text, bg = c.bg },
  },
  terminal = {
    a = { fg = c.bg, bg = c.verdigris, gui = "bold" },
    b = { fg = c.text, bg = c.surface },
    c = { fg = c.text, bg = c.bg },
  },
  inactive = {
    a = { fg = c.muted, bg = c.surface },
    b = { fg = c.muted, bg = c.surface },
    c = { fg = c.subtext, bg = c.bg },
  },
}

return M
