#!/usr/bin/env bash
# ===== Autostart =====
. ~/.config/bspwm/scripts/autostart.sh

# ===== Monitor Settings ======
# bspc monitor --swap HDMI-A-0 ^1
# bspc monitor --swap DisplayPort-0 ^2
bspc monitor DisplayPort-0 -d main dev term media misc
bspc monitor DisplayPort-1 -d web zen term media misc

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true


bspc config automatic_scheme longest_side
bspc config initial_polarity second_child

# Borders and Gaps
bspc config border_width  2
bspc config window_gap  6

bspc config top_padding 0
bspc config borderless_monocle  true
bspc config gapless_monocle false

# Focusing behaviour
bspc config focus_follows_pointer true

# source the colors.

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color5"
bspc config presel_feedback_color "$color1"

# ===== BSPC Rules =====
# Internal Rules
bspc rule -a plasmashell state=floating border=off layer=normal
bspc rule -a krunner state=floating border=off
bspc rule -a Zathura state=floating

# External rules
# Used to make some settings windows float properly
bspc config external_rules_command ~/.config/bspwm/scripts/external_rules.sh
enforce_monitor_position DisplayPort-0 '^1' &
