#! /bin/sh
sxhkd &
wal -q -i ~/onedrive/wallpapers/ &
picom --config ~/.config/picom/picom.conf -b

# Run polybar
$HOME/.config/polybar/polybar.sh &


bspc wm -O HDMI-A-0 DisplayPort-0
bspc monitor HDMI-A-0 -d I II III IV V 
bspc monitor DisplayPort-0 -d VI VII VIII IX X

bspc config automatic_scheme  longest_side
bspc config initial_polarity second_child

# Borders and Gaps
bspc config border_width         4
bspc config window_gap          12

bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Focusing behaviour
bspc config focus_follows_pointer true
bspc config history_aware_focus true
bspc config focus_by_distance true

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc rule -a plasmashell state=floating border=off layer=normal
bspc rule -a krunner state=floating border=off
