# Audio overrides — the system default (pipewire.conf) fills in everything else.
context.properties = {
    default.clock.rate                    = 48000
    default.clock.allowed-rates           = [ 384000 352800 192000 176400 96000 88200 48000 44100 ]
    default.clock.quantum                 = 256
    default.clock.min-quantum             = 32
    default.clock.max-quantum             = 2048
}